name: Shared CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nextjs:
    name: Shared Next.js CI
    uses: forbiddenlink/.github/.github/workflows/ci-nextjs.yml@3d292833fa3cdbc394db60307c8832c9b058443c
    with:
      node-version: "20"

  security:
    name: Shared Security
    uses: forbiddenlink/.github/.github/workflows/security.yml@3d292833fa3cdbc394db60307c8832c9b058443c
